<a href="https://colab.research.google.com/github/AlexandreSauze/Sydney-Data-Science-Python/blob/main/Project1_test1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd  # import panda functions
import numpy as np  # import statistic and math functions
data = pd.read_csv('Belarus Used Cars Prices.csv')  # import csv data into a Panda Data Frame
data

,make,model,priceUSD,year,condition,mileage(kilometers),fuel_type,volume(cm3),color,transmission,drive_unit,segment
0,audi,a4,3000,1996,with mileage,9999999.0,petrol,1800.0,red,mechanics,front-wheel drive,D
1,audi,100,900,1989,with mileage,9999999.0,petrol,2300.0,white,mechanics,front-wheel drive,E
2,audi,80,500,1986,with mileage,9999999.0,petrol,1800.0,silver,mechanics,front-wheel drive,D
3,bmw,7-seriya,4650,1998,with mileage,9999999.0,petrol,3000.0,green,auto,rear drive,F
4,bmw,5-seriya,2000,1985,with mileage,9999999.0,petrol,2800.0,blue,mechanics,rear drive,E
...,...,...,...,...,...,...,...,...,...,...,...,...
56239,volvo,s80,6400,2002,with mileage,0.0,diesel,2400.0,silver,auto,front-wheel drive,E
56240,volvo,940,1900,1992,with mileage,0.0,petrol,2300.0,black,mechanics,rear drive,E
56241,volvo,460,1000,1991,with mileage,0.0,petrol,1700.0,other,mechanics,front-wheel drive,C
56242,volvo,460,700,1995,with mileage,0.0,petrol,888.0,green,mechanics,front-wheel drive,C
56243,volvo,300-series,400,1987,with mileage,0.0,petrol,1700.0,gray,mechanics,rear drive,NaN

In [ ]:
data.isna().sum()  # Check if there are any Nans in each column
data.isnull().sum()  # Check if there are any blank spaces in each column

make                      0
model                     0
priceUSD                  0
year                      0
condition                 0
mileage(kilometers)       0
fuel_type                 0
volume(cm3)              47
color                     0
transmission              0
drive_unit             1905
segment                5291
dtype: int64

In [ ]:
#data = data.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)  # remove all the blank rows by using the data.dropna() function
UD = data[['make','model','priceUSD','year','mileage(kilometers)']]  # Filter the data by only keeping the columns we need
UD = UD.to_dict('records')  # Transform the Pandas Data Frame into a list where each entry is a dictionary for each row. The keys are the columns.
UD

[{'make': 'audi',
  'model': 'a4',
  'priceUSD': 3000,
  'year': 1996,
  'mileage(kilometers)': 9999999.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 900,
  'year': 1989,
  'mileage(kilometers)': 9999999.0},
 {'make': 'audi',
  'model': '80',
  'priceUSD': 500,
  'year': 1986,
  'mileage(kilometers)': 9999999.0},
 {'make': 'bmw',
  'model': '7-seriya',
  'priceUSD': 4650,
  'year': 1998,
  'mileage(kilometers)': 9999999.0},
 {'make': 'bmw',
  'model': '5-seriya',
  'priceUSD': 2000,
  'year': 1985,
  'mileage(kilometers)': 9999999.0},
 {'make': 'citroen',
  'model': 'xantia',
  'priceUSD': 879,
  'year': 1999,
  'mileage(kilometers)': 9999999.0},
 {'make': 'fiat',
  'model': 'stilo',
  'priceUSD': 3000,
  'year': 2001,
  'mileage(kilometers)': 9999999.0},
 {'make': 'fiat',
  'model': 'brava',
  'priceUSD': 1100,
  'year': 1997,
  'mileage(kilometers)': 9999999.0},
 {'make': 'ford',
  'model': 'sierra',
  'priceUSD': 143,
  'year': 1984,
  'mileage(kilometers)': 9999999.0},
 {'make': 'honda',
  'model': 'cr-v',
  'priceUSD': 7300,
  'year': 2005,
  'mileage(kilometers)': 9999999.0},
 {'make': 'lada-vaz',
  'model': '2104',
  'priceUSD': 600,
  'year': 1990,
  'mileage(kilometers)': 9999999.0},
 {'make': 'lada-vaz',
  'model': '2108',
  'priceUSD': 295,
  'year': 1990,
  'mileage(kilometers)': 9999999.0},
 {'make': 'mercedes-benz',
  'model': 'e-klass',
  'priceUSD': 1850,
  'year': 1989,
  'mileage(kilometers)': 9999999.0},
 {'make': 'nissan',
  'model': 'laurel',
  'priceUSD': 550,
  'year': 1986,
  'mileage(kilometers)': 9999999.0},
 {'make': 'nissan',
  'model': 'primera',
  'priceUSD': 500,
  'year': 1993,
  'mileage(kilometers)': 9999999.0},
 {'make': 'nissan',
  'model': 'primera',
  'priceUSD': 400,
  'year': 1991,
  'mileage(kilometers)': 9999999.0},
 {'make': 'opel',
  'model': 'omega',
  'priceUSD': 400,
  'year': 1987,
  'mileage(kilometers)': 9999999.0},
 {'make': 'opel',
  'model': 'kadett',
  'priceUSD': 250,
  'year': 1985,
  'mileage(kilometers)': 9999999.0},
 {'make': 'peugeot',
  'model': '806',
  'priceUSD': 4100,
  'year': 2000,
  'mileage(kilometers)': 9999999.0},
 {'make': 'raf',
  'model': '2203',
  'priceUSD': 1000,
  'year': 1991,
  'mileage(kilometers)': 9999999.0},
 {'make': 'renault',
  'model': 'laguna',
  'priceUSD': 1400,
  'year': 1995,
  'mileage(kilometers)': 9999999.0},
 {'make': 'volkswagen',
  'model': 'passat',
  'priceUSD': 500,
  'year': 1987,
  'mileage(kilometers)': 9999999.0},
 {'make': 'volkswagen',
  'model': 'jetta',
  'priceUSD': 8700,
  'year': 2011,
  'mileage(kilometers)': 8888888.0},
 {'make': 'nissan',
  'model': 'sunny',
  'priceUSD': 700,
  'year': 1994,
  'mileage(kilometers)': 7777777.0},
 {'make': 'volkswagen',
  'model': 'transporter',
  'priceUSD': 2950,
  'year': 1985,
  'mileage(kilometers)': 7000000.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 1500,
  'year': 1989,
  'mileage(kilometers)': 6666666.0},
 {'make': 'peugeot',
  'model': '405',
  'priceUSD': 428,
  'year': 1991,
  'mileage(kilometers)': 6666666.0},
 {'make': 'volkswagen',
  'model': 'golf',
  'priceUSD': 1450,
  'year': 1994,
  'mileage(kilometers)': 6666666.0},
 {'make': 'volkswagen',
  'model': 'golf',
  'priceUSD': 650,
  'year': 1988,
  'mileage(kilometers)': 6666666.0},
 {'make': 'volkswagen',
  'model': 'golf',
  'priceUSD': 550,
  'year': 1982,
  'mileage(kilometers)': 6666666.0},
 {'make': 'peugeot',
  'model': '405',
  'priceUSD': 230,
  'year': 1989,
  'mileage(kilometers)': 6110707.0},
 {'make': 'volkswagen',
  'model': 'vento',
  'priceUSD': 1300,
  'year': 1992,
  'mileage(kilometers)': 6000000.0},
 {'make': 'nissan',
  'model': 'serena',
  'priceUSD': 2600,
  'year': 1995,
  'mileage(kilometers)': 5689754.0},
 {'make': 'ford',
  'model': 'scorpio',
  'priceUSD': 1450,
  'year': 1997,
  'mileage(kilometers)': 5678397.0},
 {'make': 'ford',
  'model': 'mondeo',
  'priceUSD': 1400,
  'year': 1996,
  'mileage(kilometers)': 5600000.0},
 {'make': 'audi',
  'model': '80',
  'priceUSD': 3000,
  'year': 1993,
  'mileage(kilometers)': 5555555.0},
 {'make': 'bmw',
  'model': '3-seriya',
  'priceUSD': 2600,
  'year': 1998,
  'mileage(kilometers)': 5555555.0},
 {'make': 'mercedes-benz',
  'model': 'e-klass',
  'priceUSD': 1800,
  'year': 1987,
  'mileage(kilometers)': 5555555.0},
 {'make': 'nissan',
  'model': 'primera',
  'priceUSD': 761,
  'year': 1994,
  'mileage(kilometers)': 5555555.0},
 {'make': 'rover',
  'model': '600',
  'priceUSD': 800,
  'year': 1999,
  'mileage(kilometers)': 5555555.0},
 {'make': 'volkswagen',
  'model': 'multivan',
  'priceUSD': 3900,
  'year': 1992,
  'mileage(kilometers)': 5555555.0},
 {'make': 'volkswagen',
  'model': 'passat',
  'priceUSD': 1100,
  'year': 1990,
  'mileage(kilometers)': 5555555.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 2500,
  'year': 1989,
  'mileage(kilometers)': 5445558.0},
 {'make': 'renault',
  'model': 'scenic',
  'priceUSD': 2300,
  'year': 1999,
  'mileage(kilometers)': 5300000.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 500,
  'year': 1985,
  'mileage(kilometers)': 5231758.0},
 {'make': 'seat',
  'model': 'ibiza',
  'priceUSD': 800,
  'year': 1995,
  'mileage(kilometers)': 5000005.0},
 {'make': 'peugeot',
  'model': '405',
  'priceUSD': 400,
  'year': 1991,
  'mileage(kilometers)': 5000000.0},
 {'make': 'volkswagen',
  'model': 'passat',
  'priceUSD': 2999,
  'year': 1996,
  'mileage(kilometers)': 5000000.0},
 {'make': 'volkswagen',
  'model': 'golf',
  'priceUSD': 523,
  'year': 1986,
  'mileage(kilometers)': 4999999.0},
 {'make': 'seat',
  'model': 'toledo',
  'priceUSD': 1300,
  'year': 1992,
  'mileage(kilometers)': 4900000.0},
 {'make': 'bmw',
  'model': '5-seriya',
  'priceUSD': 4800,
  'year': 2001,
  'mileage(kilometers)': 4786446.0},
 {'make': 'opel',
  'model': 'astra',
  'priceUSD': 1400,
  'year': 1992,
  'mileage(kilometers)': 4667086.0},
 {'make': 'mazda',
  'model': 'mx-3',
  'priceUSD': 1000,
  'year': 1995,
  'mileage(kilometers)': 4566545.0},
 {'make': 'audi',
  'model': 'a6',
  'priceUSD': 3000,
  'year': 1997,
  'mileage(kilometers)': 4500000.0},
 {'make': 'renault',
  'model': 'laguna',
  'priceUSD': 800,
  'year': 1997,
  'mileage(kilometers)': 4500000.0},
 {'make': 'opel',
  'model': 'astra',
  'priceUSD': 2500,
  'year': 2000,
  'mileage(kilometers)': 4470000.0},
 {'make': 'bmw',
  'model': '3-seriya',
  'priceUSD': 2500,
  'year': 1997,
  'mileage(kilometers)': 4444523.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 1500,
  'year': 1984,
  'mileage(kilometers)': 4444445.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 1500,
  'year': 1983,
  'mileage(kilometers)': 4444444.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 1500,
  'year': 1992,
  'mileage(kilometers)': 4444444.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 600,
  'year': 1984,
  'mileage(kilometers)': 4444444.0},
 {'make': 'citroen',
  'model': 'evasion',
  'priceUSD': 3200,
  'year': 1999,
  'mileage(kilometers)': 4444444.0},
 {'make': 'mercedes-benz',
  'model': 'c-klass',
  'priceUSD': 1250,
  'year': 1994,
  'mileage(kilometers)': 4444444.0},
 {'make': 'opel',
  'model': 'zafira',
  'priceUSD': 4850,
  'year': 2004,
  'mileage(kilometers)': 4444444.0},
 {'make': 'volkswagen',
  'model': 'jetta',
  'priceUSD': 950,
  'year': 1991,
  'mileage(kilometers)': 4444444.0},
 {'make': 'volvo',
  'model': '440',
  'priceUSD': 500,
  'year': 1990,
  'mileage(kilometers)': 4444444.0},
 {'make': 'bmw',
  'model': '5-seriya',
  'priceUSD': 1000,
  'year': 1991,
  'mileage(kilometers)': 4400000.0},
 {'make': 'opel',
  'model': 'astra',
  'priceUSD': 1100,
  'year': 1997,
  'mileage(kilometers)': 4300000.0},
 {'make': 'mitsubishi',
  'model': 'carisma',
  'priceUSD': 1200,
  'year': 1998,
  'mileage(kilometers)': 4250000.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 2600,
  'year': 1993,
  'mileage(kilometers)': 4157000.0},
 {'make': 'hyundai',
  'model': 'santa-fe',
  'priceUSD': 5900,
  'year': 2002,
  'mileage(kilometers)': 4100000.0},
 {'make': 'honda',
  'model': 'stream',
  'priceUSD': 4300,
  'year': 2001,
  'mileage(kilometers)': 4050000.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 1000,
  'year': 1986,
  'mileage(kilometers)': 4000000.0},
 {'make': 'audi',
  'model': '80',
  'priceUSD': 550,
  'year': 1986,
  'mileage(kilometers)': 4000000.0},
 {'make': 'bmw',
  'model': '5-seriya',
  'priceUSD': 2150,
  'year': 1991,
  'mileage(kilometers)': 4000000.0},
 {'make': 'bmw',
  'model': '5-seriya',
  'priceUSD': 1600,
  'year': 1993,
  'mileage(kilometers)': 4000000.0},
 {'make': 'fiat',
  'model': 'tempra',
  'priceUSD': 500,
  'year': 1992,
  'mileage(kilometers)': 4000000.0},
 {'make': 'mercedes-benz',
  'model': 'e-klass',
  'priceUSD': 2300,
  'year': 1987,
  'mileage(kilometers)': 4000000.0},
 {'make': 'volkswagen',
  'model': 'golf',
  'priceUSD': 2700,
  'year': 1997,
  'mileage(kilometers)': 4000000.0},
 {'make': 'volkswagen',
  'model': 'passat',
  'priceUSD': 1400,
  'year': 1991,
  'mileage(kilometers)': 4000000.0},
 {'make': 'volkswagen',
  'model': 'golf',
  'priceUSD': 999,
  'year': 1985,
  'mileage(kilometers)': 4000000.0},
 {'make': 'volkswagen',
  'model': 'passat',
  'priceUSD': 900,
  'year': 1990,
  'mileage(kilometers)': 4000000.0},
 {'make': 'bmw',
  'model': '3-seriya',
  'priceUSD': 2050,
  'year': 1998,
  'mileage(kilometers)': 3900000.0},
 {'make': 'mercedes-benz',
  'model': '190-w201',
  'priceUSD': 750,
  'year': 1991,
  'mileage(kilometers)': 3865745.0},
 {'make': 'chrysler',
  'model': 'stratus',
  'priceUSD': 1200,
  'year': 1995,
  'mileage(kilometers)': 3863559.0},
 {'make': 'seat',
  'model': 'alhambra',
  'priceUSD': 6200,
  'year': 2001,
  'mileage(kilometers)': 3780000.0},
 {'make': 'citroen',
  'model': 'xsara-picasso',
  'priceUSD': 3500,
  'year': 2001,
  'mileage(kilometers)': 3748301.0},
 {'make': 'audi',
  'model': '80',
  'priceUSD': 1400,
  'year': 1986,
  'mileage(kilometers)': 3700490.0},
 {'make': 'audi',
  'model': '80',
  'priceUSD': 1500,
  'year': 1988,
  'mileage(kilometers)': 3700000.0},
 {'make': 'ford',
  'model': 'focus',
  'priceUSD': 1650,
  'year': 2000,
  'mileage(kilometers)': 3700000.0},
 {'make': 'volkswagen',
  'model': 'golf',
  'priceUSD': 3000,
  'year': 1999,
  'mileage(kilometers)': 3700000.0},
 {'make': 'volkswagen',
  'model': 'golf',
  'priceUSD': 400,
  'year': 1989,
  'mileage(kilometers)': 3700000.0},
 {'make': 'ford',
  'model': 'mondeo',
  'priceUSD': 1300,
  'year': 1999,
  'mileage(kilometers)': 3660000.0},
 {'make': 'volkswagen',
  'model': 'passat',
  'priceUSD': 1200,
  'year': 1988,
  'mileage(kilometers)': 3654674.0},
 {'make': 'mercedes-benz',
  'model': 'e-klass',
  'priceUSD': 5300,
  'year': 2002,
  'mileage(kilometers)': 3600000.0},
 {'make': 'opel',
  'model': 'zafira',
  'priceUSD': 4000,
  'year': 1999,
  'mileage(kilometers)': 3600000.0},
 {'make': 'opel',
  'model': 'omega',
  'priceUSD': 1400,
  'year': 1998,
  'mileage(kilometers)': 3600000.0},
 {'make': 'nissan',
  'model': 'primera',
  'priceUSD': 1000,
  'year': 1996,
  'mileage(kilometers)': 3567886.0},
 {'make': 'citroen',
  'model': 'xsara',
  'priceUSD': 2000,
  'year': 1998,
  'mileage(kilometers)': 3566825.0},
 {'make': 'kia',
  'model': 'sorento',
  'priceUSD': 4200,
  'year': 2003,
  'mileage(kilometers)': 3560000.0},
 {'make': 'audi',
  'model': 'a4',
  'priceUSD': 5000,
  'year': 2003,
  'mileage(kilometers)': 3555555.0},
 {'make': 'renault',
  'model': 'laguna',
  'priceUSD': 950,
  'year': 1997,
  'mileage(kilometers)': 3550000.0},
 {'make': 'bmw',
  'model': '5-seriya',
  'priceUSD': 1800,
  'year': 1991,
  'mileage(kilometers)': 3500000.0},
 {'make': 'peugeot',
  'model': '806',
  'priceUSD': 3000,
  'year': 1998,
  'mileage(kilometers)': 3500000.0},
 {'make': 'renault',
  'model': 'safrane',
  'priceUSD': 1200,
  'year': 1995,
  'mileage(kilometers)': 3500000.0},
 {'make': 'volkswagen',
  'model': 'jetta',
  'priceUSD': 400,
  'year': 1988,
  'mileage(kilometers)': 3500000.0},
 {'make': 'bmw',
  'model': '3-seriya',
  'priceUSD': 1000,
  'year': 1992,
  'mileage(kilometers)': 3497319.0},
 {'make': 'bmw',
  'model': '5-seriya',
  'priceUSD': 5000,
  'year': 1999,
  'mileage(kilometers)': 3472863.0},
 {'make': 'mercedes-benz',
  'model': 'e-klass',
  'priceUSD': 700,
  'year': 1982,
  'mileage(kilometers)': 3466654.0},
 {'make': 'ford',
  'model': 'mondeo',
  'priceUSD': 666,
  'year': 1993,
  'mileage(kilometers)': 3456789.0},
 {'make': 'opel',
  'model': 'vectra',
  'priceUSD': 700,
  'year': 1992,
  'mileage(kilometers)': 3456755.0},
 {'make': 'opel',
  'model': 'vectra',
  'priceUSD': 700,
  'year': 1992,
  'mileage(kilometers)': 3456750.0},
 {'make': 'volkswagen',
  'model': 'passat',
  'priceUSD': 600,
  'year': 1990,
  'mileage(kilometers)': 3452765.0},
 {'make': 'ford',
  'model': 'mondeo',
  'priceUSD': 750,
  'year': 1993,
  'mileage(kilometers)': 3444444.0},
 {'make': 'mazda',
  'model': '323f',
  'priceUSD': 600,
  'year': 1980,
  'mileage(kilometers)': 3444444.0},
 {'make': 'mercedes-benz',
  'model': '190-w201',
  'priceUSD': 1200,
  'year': 1985,
  'mileage(kilometers)': 3434333.0},
 {'make': 'citroen',
  'model': 'xsara',
  'priceUSD': 700,
  'year': 1998,
  'mileage(kilometers)': 3421976.0},
 {'make': 'kia',
  'model': 'clarus',
  'priceUSD': 1250,
  'year': 2000,
  'mileage(kilometers)': 3400000.0},
 {'make': 'bmw',
  'model': '7-seriya',
  'priceUSD': 3500,
  'year': 1994,
  'mileage(kilometers)': 3376558.0},
 {'make': 'volkswagen',
  'model': 'jetta',
  'priceUSD': 550,
  'year': 1987,
  'mileage(kilometers)': 3375826.0},
 {'make': 'fiat',
  'model': 'marea',
  'priceUSD': 500,
  'year': 1999,
  'mileage(kilometers)': 3333344.0},
 {'make': 'audi',
  'model': '80',
  'priceUSD': 3000,
  'year': 1994,
  'mileage(kilometers)': 3333333.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 1000,
  'year': 1987,
  'mileage(kilometers)': 3333333.0},
 {'make': 'audi',
  'model': '80',
  'priceUSD': 900,
  'year': 1988,
  'mileage(kilometers)': 3333333.0},
 {'make': 'bmw',
  'model': '3-seriya',
  'priceUSD': 1900,
  'year': 1993,
  'mileage(kilometers)': 3333333.0},
 {'make': 'bmw',
  'model': '3-seriya',
  'priceUSD': 1800,
  'year': 1996,
  'mileage(kilometers)': 3333333.0},
 {'make': 'bmw',
  'model': '5-seriya',
  'priceUSD': 700,
  'year': 1995,
  'mileage(kilometers)': 3333333.0},
 {'make': 'ford',
  'model': 'fiesta',
  'priceUSD': 500,
  'year': 1990,
  'mileage(kilometers)': 3333333.0},
 {'make': 'kia',
  'model': 'sephia',
  'priceUSD': 547,
  'year': 1993,
  'mileage(kilometers)': 3333333.0},
 {'make': 'lada-vaz',
  'model': '2109',
  'priceUSD': 400,
  'year': 1988,
  'mileage(kilometers)': 3333333.0},
 {'make': 'lancia',
  'model': 'zeta',
  'priceUSD': 3750,
  'year': 1998,
  'mileage(kilometers)': 3333333.0},
 {'make': 'land-rover',
  'model': 'range-rover',
  'priceUSD': 4100,
  'year': 1997,
  'mileage(kilometers)': 3333333.0},
 {'make': 'mitsubishi',
  'model': 'galant',
  'priceUSD': 1050,
  'year': 1989,
  'mileage(kilometers)': 3333333.0},
 {'make': 'opel',
  'model': 'vectra',
  'priceUSD': 6450,
  'year': 2007,
  'mileage(kilometers)': 3333333.0},
 {'make': 'opel',
  'model': 'vectra',
  'priceUSD': 6450,
  'year': 2007,
  'mileage(kilometers)': 3333333.0},
 {'make': 'opel',
  'model': 'zafira',
  'priceUSD': 4400,
  'year': 2002,
  'mileage(kilometers)': 3333333.0},
 {'make': 'renault',
  'model': 'laguna',
  'priceUSD': 2000,
  'year': 1997,
  'mileage(kilometers)': 3333333.0},
 {'make': 'renault',
  'model': 'laguna',
  'priceUSD': 1800,
  'year': 1997,
  'mileage(kilometers)': 3333333.0},
 {'make': 'renault',
  'model': 'laguna',
  'priceUSD': 1500,
  'year': 1998,
  'mileage(kilometers)': 3333333.0},
 {'make': 'saab',
  'model': '09-Mar',
  'priceUSD': 4000,
  'year': 2002,
  'mileage(kilometers)': 3333333.0},
 {'make': 'volkswagen',
  'model': 'sharan',
  'priceUSD': 4500,
  'year': 1998,
  'mileage(kilometers)': 3333333.0},
 {'make': 'volkswagen',
  'model': 'passat',
  'priceUSD': 3800,
  'year': 1999,
  'mileage(kilometers)': 3333333.0},
 {'make': 'volkswagen',
  'model': 'transporter',
  'priceUSD': 1700,
  'year': 1989,
  'mileage(kilometers)': 3333333.0},
 {'make': 'volkswagen',
  'model': 'jetta',
  'priceUSD': 900,
  'year': 1991,
  'mileage(kilometers)': 3333333.0},
 {'make': 'volkswagen',
  'model': 'transporter',
  'priceUSD': 350,
  'year': 1986,
  'mileage(kilometers)': 3333333.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 2300,
  'year': 1992,
  'mileage(kilometers)': 3310000.0},
 {'make': 'peugeot',
  'model': '307',
  'priceUSD': 4000,
  'year': 2004,
  'mileage(kilometers)': 3270000.0},
 {'make': 'mitsubishi',
  'model': 'carisma',
  'priceUSD': 1600,
  'year': 1998,
  'mileage(kilometers)': 3258445.0},
 {'make': 'volvo',
  'model': '940',
  'priceUSD': 2500,
  'year': 1998,
  'mileage(kilometers)': 3250000.0},
 {'make': 'nissan',
  'model': 'patrol',
  'priceUSD': 2700,
  'year': 1993,
  'mileage(kilometers)': 3222564.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 1150,
  'year': 1991,
  'mileage(kilometers)': 3200000.0},
 {'make': 'volkswagen',
  'model': 'passat',
  'priceUSD': 3300,
  'year': 1997,
  'mileage(kilometers)': 3200000.0},
 {'make': 'citroen',
  'model': 'c5',
  'priceUSD': 3700,
  'year': 2002,
  'mileage(kilometers)': 3180000.0},
 {'make': 'renault',
  'model': 'megane',
  'priceUSD': 1200,
  'year': 1997,
  'mileage(kilometers)': 3165646.0},
 {'make': 'daewoo',
  'model': 'espero',
  'priceUSD': 700,
  'year': 1997,
  'mileage(kilometers)': 3152527.0},
 {'make': 'opel',
  'model': 'vectra',
  'priceUSD': 2250,
  'year': 1999,
  'mileage(kilometers)': 3150000.0},
 {'make': 'toyota',
  'model': 'corolla',
  'priceUSD': 500,
  'year': 1994,
  'mileage(kilometers)': 3121567.0},
 {'make': 'audi',
  'model': 'a6',
  'priceUSD': 9270,
  'year': 2005,
  'mileage(kilometers)': 3000000.0},
 {'make': 'audi',
  'model': '80',
  'priceUSD': 1299,
  'year': 1989,
  'mileage(kilometers)': 3000000.0},
 {'make': 'audi',
  'model': '100',
  'priceUSD': 1100,
  'year': 1988,
  'mileage(kilometers)': 3000000.0},
 {'make': 'bmw',
  'model': '3-seriya',
  'priceUSD': 700,
  'year': 1987,
  'mileage(kilometers)': 3000000.0},
 {'make': 'lada-vaz',
  'model': '2106',
  'priceUSD': 600,
  'year': 1985,
  'mileage(kilometers)': 3000000.0},
 {'make': 'mercedes-benz',
  'model': 'vito',
  'priceUSD': 6800,
  'year': 1999,
  'mileage(kilometers)': 3000000.0},
 {'make': 'mercedes-benz',
  'model': '190-w201',
  'priceUSD': 350,
  'year': 1988,
  'mileage(kilometers)': 3000000.0},
 {'make': 'opel',
  'model': 'kadett',
  'priceUSD': 300,
  'year': 1988,
  'mileage(kilometers)': 3000000.0},
 {'make': 'peugeot',
  'model': '407',
  'priceUSD': 4100,
  'year': 2005,
  'mileage(kilometers)': 3000000.0},
 {'make': 'renault',
  'model': 'laguna',
  'priceUSD': 2400,
  'year': 2000,
  'mileage(kilometers)': 3000000.0},
 {'make': 'renault',
  'model': 'laguna',
  'priceUSD': 1000,
  'year': 1997,
  'mileage(kilometers)': 3000000.0},
 {'make': 'seat',
  'model': 'cordoba',
  'priceUSD': 856,
  'year': 1997,
  'mileage(kilometers)': 3000000.0},
 {'make': 'volkswagen',
  'model': 'passat',
  'priceUSD': 3850,
  'year': 1997,
  'mileage(kilometers)': 3000000.0},
 {'make': 'volkswagen',
  'model': 'santana',
  'priceUSD': 166,
  'year': 1983,
  'mileage(kilometers)': 3000000.0},
 {'make': 'volvo',
  'model': 's80',
  'priceUSD': 5000,
  'year': 2000,
  'mileage(kilometers)': 3000000.0},
 {'make': 'renault',
  'model': 'safrane',
  'priceUSD': 1050,
  'year': 1993,
  'mileage(kilometers)': 2999999.0},
 {'make': 'mazda',
  'model': '323',
  'priceUSD': 1000,
  'year': 1995,
  'mileage(kilometers)': 2989500.0},
 {'make': 'hyundai',
  'model': 'santamo',
  'priceUSD': 2200,
  'year': 1997,
  'mileage(kilometers)': 2954878.0},
 {'make': 'audi',
  'model': 'a4',
  'priceUSD': 6900,
  'year': 2005,
  'mileage(kilometers)': 2900000.0},
 {'make': 'mercedes-benz',

In [ ]:
UD = data[['make','model','priceUSD','year','mileage(kilometers)']]  # Filter the data by only keeping the columns we need
UD = UD.to_dict('records')  # Transform the Pandas Data Frame into a list where each entry is a dictionary for each row. The keys are the columns.

c = 0  # counter
tf = True
for row in UD:  # We then create a list for each column to facilitate data manipulation
  if tf:
    tf = False
    Brand = [row['make']]
    Model = [row['model']]
    Year = [row['year']]
    Price = [row['priceUSD']]
    Mileage = [row['mileage(kilometers)']]
  else:
    Brand.append(row['make'])
    Model.append(row['model'])
    Year.append(row['year'])
    Price.append(row['priceUSD'])
    Mileage.append(row['mileage(kilometers)'])
  c += 1
print('Biggest year:',max(Year))  # We then review the maxs and mins
print('Shortest year:',min(Year))
print('Most expensive:',max(Price))
print('Cheapest:',min(Price))

Biggest year: 2019
Shortest year: 1910
Most expensive: 235235
Cheapest: 48

In [ ]:
# Outlier identification function
def Outlier_IQR(info):
  info = sorted(info)
  outlier = []
  Q1 = len(info)//4-1
  Q2 = int(len(info)/2-1)
  Q3 = 3*len(info)//4-1
  Q4 = len(info)-1
  iQ1 = info[Q1]
  iQ2 = np.mean([info[Q2],info[Q2+1]])
  iQ3 = info[Q3]
  iQ4 = info[Q4]
  IQR = iQ3-iQ1
  #print(Q1,Q3,Q3-Q1-2,Q2)
  print("Q0:",info[0],"\nQ1:",iQ1,"\nQ2:",iQ2,"\nQ3:",iQ3,"\nQ4:",iQ4)
  lb = iQ1 - (1.5 * IQR)
  ub = iQ3 + (1.5 * IQR)

  print("Lower bound:",lb)
  print("Upper bound:", ub)

  for item in info:
    if item < lb or item > ub:
      outlier.append(item)
  print("There are",len(outlier),"outliers\n")
  return outlier

In [ ]:
Price_Outliers = Outlier_IQR(Price)  #We save the price outliers in a list
Year_Outliers = Outlier_IQR(Year)  #We save the year outliers in a list
Mileage_Outliers = Outlier_IQR(Mileage)  #We save the Mileage outliers in a list

Q0: 48
Q1: 2350
Q2: 5350.0
Q3: 9800
Q4: 235235
Lower bound: -8825.0
Upper bound: 20975.0
There are 2555 outliers

Q0: 1910
Q1: 1998
Q2: 2004.0
Q3: 2010
Q4: 2019
Lower bound: 1980.0
Upper bound: 2028.0
There are 258 outliers

Q0: 0.0
Q1: 137000.0
Q2: 228500.0
Q3: 310000.0
Q4: 9999999.0
Lower bound: -122500.0
Upper bound: 569500.0
There are 689 outliers

In [ ]:
df = data[~data['priceUSD'].isin(Price_Outliers)]  #We now remove the rows with the values containing the outliers
df1 = df[~df['year'].isin(Year_Outliers)]
df2 = df1[~df1['mileage(kilometers)'].isin(Mileage_Outliers)]
df3 = df2[['make','model','priceUSD','year','mileage(kilometers)']]
df3.to_csv('Belarus Used Cars Prices_clean.csv',index=False)  #We now import our dataframe as a new csv file

In [ ]:
print("Maximum Price:",max(df3['priceUSD']),"$","     Minimum Price:",min(df3['priceUSD']),"$")
print("Maximum Year:",max(df3['year']),"     Minimum Year:",min(df3['year']))
print("Maximum Mileage:",max(df3['mileage(kilometers)']),"km","     Minimum Mileage:",min(df3['mileage(kilometers)']),"km")
manu = {}
maker = df3['make']
for brand in maker:
  if brand not in manu:
    manu[brand] = 1
  else:
    manu[brand] += 1
for key in manu:
  print(key+":",manu[key])

Maximum Price: 20970 $      Minimum Price: 95 $
Maximum Year: 2019      Minimum Year: 1980
Maximum Mileage: 568956.0 km      Minimum Mileage: 0.0 km
acura: 88
alfa-romeo: 225
aro: 2
asia: 1
audi: 3724
bmw: 3498
bogdan: 1
brilliance: 2
buick: 82
byd: 3
cadillac: 55
changan: 4
chery: 83
chevrolet: 577
chrysler: 507
citroen: 1971
dacia: 74
daewoo: 314
daihatsu: 33
datsun: 17
dong-feng: 1
eksklyuziv: 41
faw: 3
fiat: 922
ford: 2970
fso: 3
gaz: 113
geely: 83
gmc: 17
great-wall: 66
hafei: 6
haval: 4
honda: 919
hyundai: 1433
infiniti: 217
iran-khodro: 13
isuzu: 25
izh: 13
jac: 1
jaguar: 44
jeep: 179
kia: 1141
lada-vaz: 932
lancia: 114
land-rover: 242
lexus: 249
lifan: 82
lincoln: 35
luaz: 29
maserati: 2
mazda: 1942
mercedes-benz: 2978
mercury: 7
mg: 7
mini: 85
mitsubishi: 1298
moskvich: 30
nissan: 2163
oldsmobile: 2
opel: 3737
peugeot: 2850
plymouth: 14
pontiac: 31
porsche: 86
proton: 21
raf: 1
ravon: 12
renault: 3662
roewe: 1
rover: 299
saab: 125
saipa: 1
saturn: 17
scion: 9
seat: 464
shanghai-maple: 1
skoda: 1112
smart: 29
ssangyong: 139
subaru: 360
suzuki: 330
tagaz: 1
tata: 2
toyota: 1894
uaz: 129
volkswagen: 6548
volvo: 1138
vortex: 6
wartburg: 5
zaz: 58
zotye: 4